### ISSUE TITLE
Volunteer form missing

### ISSUE THREAD

**Issue by kernelmethod** [punkcoder/site.bsidesboulder#27]
`content/pages/volunteers.md` ([link](https://github.com/punkcoder/site.bsidesboulder/blob/144a9526cbe5205b74eaf34fb2881bee3a93d585/content/pages/volunteers.md)) seems to reference a shortcode `{{< volunteerform >}}` that isn't defined anywhere in the source. As a result the volunteer form isn't showing up on the volunteer page (https://bsidesboulder.org/volunteers):

![Screenshot from 2020-02-13 12-06-39](https://user-images.githubusercontent.com/17100608/74469157-539bd980-4e59-11ea-84b7-a04d067cd125.png)

**Comment by punkcoder** [comment]
@kernelmethod This should be completely fixed now, can you confirm?

**Comment by kernelmethod** [comment]
Yep, it's fixed.
