### ISSUE TITLE
Upgrade jQuery to version 3.5

### ISSUE THREAD

**Issue by punkcoder** [punkcoder/site.bsidesboulder#31]

**Comment by punkcoder** [comment]
@kernelmethod when you get a chance can you check to make sure I didn't break the site.  Small update upgrading jQuery to a version without a security issue and looks good on my side but I don't trust things.

**Comment by kernelmethod** [comment]
Looks good to me; it doesn't look like it broken anything on mobile either.

**Comment by punkcoder** [comment]
Thanks for the assist.
