### ISSUE TITLE
Text Edits - there's a few instances where special characters turned weird on the site (EX: "Weâ€™ve")

### ISSUE THREAD

**Issue by punkcoder** [punkcoder/site.bsidesboulder#44]

**Comment by punkcoder** [comment]
This issue is related to people using word and it replaces a single quote with a unicode character for a tilted quote, which explodes on the web.  I think I've got them all, @akschoenbauer please take a look to confirm.

**Comment by akschoenbauer** [comment]
It looks like most have been fixed! I did notice one on the Workshops page, under the Overview heading (" â€œassume breachâ€"). Other than that though, looks great!

**Comment by punkcoder** [comment]
Awesome! Got the last one... after talking with David French not sure if the workshop page is going to survive since they changed format to a CTF.
