### ISSUE TITLE
About Page - perhaps replace the logo/image with the main logo we are using for consistency across the whole site

### ISSUE THREAD

**Issue by punkcoder** [punkcoder/site.bsidesboulder#45]

**Comment by punkcoder** [comment]
@akschoenbauer I went through and replaced some of the imagery for the page to separate out the 2020 Conference, the BSides Community, and our 501c3.  I need to get a better copy of the Logos for the 2020 and BSides community sections.

**Comment by akschoenbauer** [comment]
Awesome! It's already less convoluted, and I think once you have better quality images of the other logos, it will be even better.
