### ISSUE TITLE
Add More Imagery - maybe add a header image to each page?

### ISSUE THREAD

**Issue by punkcoder** [punkcoder/site.bsidesboulder#46]

**Comment by punkcoder** [comment]
@akschoenbauer thoughts or suggestions? I'm not opposed to the idea, just not sure what to do with it. I don't want to add the cover image to each page since that will be problematic for mobile maybe something in the 50-80px range?

**Comment by akschoenbauer** [comment]
Honestly, after looking through the newly edited site, I think it's actually fine as is. Now that the text and information is more fleshed out, I think it flows much better than before. The only image-related thing I noticed this time around was on the speakers page. If at all possible, I think it would be beneficial to remind speakers to submit a headshot for this page, as it will look way more finalized and professional once most/all speakers have images!
