### ISSUE TITLE
Home Page - Change Image and/or Opacity behind big logo (I like the logo & countdown being there, it's just a bit busy with the current background image)

### ISSUE THREAD

**Issue by punkcoder** [punkcoder/site.bsidesboulder#47]

**Comment by punkcoder** [comment]
@akschoenbauer I went through and muted the background see if that looks better.

**Comment by punkcoder** [comment]
I also went through and cleaned up the edging for the logo since it's on black background.

**Comment by akschoenbauer** [comment]
It looks a ton better now! I think it's great now. 👍
