### ISSUE TITLE
Fix mobile view

### ISSUE THREAD

**Issue by punkcoder** [punkcoder/site.bsidesboulder#7]

**Comment by punkcoder** [comment]
* Header is broken
* Hamburger is broken
* Viewport is broken

**Comment by neiltylerbell** [comment]
Seeing some weird text in the header as well as some strange characters in the body of text using Firefox (68.0.2) on Macbook Pro.

<img width="1445" alt="Screen Shot 2019-09-10 at 8 42 40 AM" src="https://user-images.githubusercontent.com/2046996/64624172-7d7f3a80-d3a7-11e9-8f70-cd12f1c7e1b3.png">

**Comment by punkcoder** [comment]
I was missing the character encoding which made it render properly locally but not in the cloud.
